class CityStateMapping {
  static Map<String, String> cityToStateCode = {
    "Adana": "TR01",
    "Adıyaman": "TR02",
    "Afyonkarahisar": "TR03",
    "Ağrı": "TR04",
    "Aksaray": "TR68",
    "Amasya": "TR05",
    "Ankara": "TR06",
    "Antalya": "TR07",
    "Ardahan": "TR75",
    "Artvin": "TR08",
    "Aydın": "TR09",
    "Balıkesir": "TR10",
    "Bartın": "TR74",
    "Batman": "TR72",
    "Bayburt": "TR69",
    "Bilecik": "TR11",
    "Bingöl": "TR12",
    "Bitlis": "TR13",
    "Bolu": "TR14",
    "Burdur": "TR15",
    "Bursa": "TR16",
    "Çanakkale": "TR17",
    "Çankırı": "TR18",
    "Çorum": "TR19",
    "Denizli": "TR20",
    "Diyarbakır": "TR21",
    "Düzce": "TR81",
    "Edirne": "TR22",
    "Elazığ": "TR23",
    "Erzincan": "TR24",
    "Erzurum": "TR25",
    "Eskişehir": "TR26",
    "Gaziantep": "TR27",
    "Giresun": "TR28",
    "Gümüşhane": "TR29",
    "Hakkari": "TR30",
    "Hatay": "TR31",
    "Iğdır": "TR76",
    "Isparta": "TR32",
    "Mersin": "TR33",
    "İstanbul": "TR34",
    "İzmir": "TR35",
    "Kahramanmaraş": "TR46",
    "Karabük": "TR78",
    "Karaman": "TR70",
    "Kars": "TR36",
    "Kastamonu": "TR37",
    "Kayseri": "TR38",
    "Kırıkkale": "TR71",
    "Kırklareli": "TR39",
    "Kırşehir": "TR40",
    "Kilis": "TR79",
    "Kocaeli": "TR41",
    "Konya": "TR42",
    "Kütahya": "TR43",
    "Malatya": "TR44",
    "Manisa": "TR45",
    "Mardin": "TR47",
    "Muğla": "TR48",
    "Muş": "TR49",
    "Nevşehir": "TR50",
    "Niğde": "TR51",
    "Ordu": "TR52",
    "Osmaniye": "TR80",
    "Rize": "TR53",
    "Sakarya": "TR54",
    "Samsun": "TR55",
    "Siirt": "TR56",
    "Sinop": "TR57",
    "Sivas": "TR58",
    "Şanlıurfa": "TR63",
    "Şırnak": "TR73",
    "Tekirdağ": "TR59",
    "Tokat": "TR60",
    "Trabzon": "TR61",
    "Tunceli": "TR62",
    "Uşak": "TR64",
    "Van": "TR65",
    "Yalova": "TR77",
    "Yozgat": "TR66",
    "Zonguldak": "TR67",
  };

  static String? getStateCode(String city) {
    return cityToStateCode[city];
  }

  static List<String> getCities() {
    return cityToStateCode.keys.toList();
  }
}
